version: '3.1'
services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - chromadb_data:/chroma/.chroma/index

  chatollama:
    environment:
      - CHROMADB_URL=http://chromadb:8000
      - DATABASE_URL=file:/app/sqlite/chatollama.sqlite
    image: registry.cn-hangzhou.aliyuncs.com/rag_web/rag_web:7bb9dc90f23690bf7294ad7586eacea10d16895e8d39fa690f26ab4796aa4310
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ~/.chatollama:/app/sqlite

volumes:
  chromadb_data:
